name: Bateria mobile build
run-name: ${{ github.actor }} is building the Bateria mobile app

on:
  push:
    branches: [ master, 21-set-up-cicd-to-build-the-app ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.3.2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run the generators
        run: flutter pub run build_runner build

      - name: Analyze the project
        run: dart analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release
